### ISSUE TITLE
Modify tab is not working with cleared labels

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbology#137]
@csmoore @nfeuerstein @lfunkhouser  FYI

When I select a symbol on the modify tab, I edit symbol and label components as expected. The only thing I can't do is if I try and remove text from the label boxes in the label tab so that they become blank, nothing happens when I click the "Save Edits" button. 

I can change text and those changes will be committed, I can add text to a new label box that was previously blank, but I can't highlight a label in the label box, click backspace/delete, and see my changes.

To reproduce: 
have mil standard symbols that have labels (unique designation, staff comments, date/time, speed, additional info, etc.) on the map in pro
navigate to modify tab in mil symbol editor
select a symbol that has labels
click forward tab twice (or navigate to label tab at the top of the pane)
remove all the labels from the label text boxes
click save edits.

nothing happens for me. 

![image](https://cloud.githubusercontent.com/assets/13024357/22165158/3cde7b74-df0f-11e6-9c02-a03facb358e2.png)

**Comment by Dbarnes1** [comment]
we can log this as a known issue with instructions to going into the attribute tab and removing the labels, this will work. @lfunkhouser and I just discussed this possibility.

**Comment by Dbarnes1** [comment]
this has been documented in the known issues section.

**Comment by dfoll** [comment]
fix worked partially... for labels such as unique designation, staff comments, or anything else that is entered as straight up text.... ie use the keyboard, or copy/paste to enter it, is is fixed. The problem remains of MSE having no way to return values that were from a drop-down or picker ... ie ...  the reinforced field, or date/time valid. You can however use the attribute window to reset those values, because using the attribute window, you have the option to select <Null> were as MSE only gives you the possible values, with not option to set to <Null>.

**Comment by dfoll** [comment]
set to version-after next, as this was an issue we already and it's already in the known issues list.

**Comment by csmoore** [comment]
OK, for the values with a domain attached we'll need to add a `"<Null>"` entry like the Attribute Editor/Table (below).

I was intentionally skipping the domain ones since setting these fields to null was causing a crash, but there must be some other method to nullify these entries.

![image](https://cloud.githubusercontent.com/assets/3090809/26644164/d3940b20-4601-11e7-8e0f-5b473074c275.png)

**Comment by dfoll** [comment]
1. There is no longer a modify tab
2. Issue is no longer reproducible given these equivalent steps since Modify tab was removed
   1. have mil standard symbols that have labels (unique designation, staff comments, date/time, speed, additional info, etc.) on the map in pro
navigate to modify tab in mil symbol editor
select a symbol that has labels
click forward tab twice (or navigate to label tab at the top of the pane)
remove all the labels from the label text boxes
click save edits.
