### ISSUE TITLE
After removing the military symbology schema from the TOC there is no way to interact with MSE again within that project

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbology#242]
After you remove the "Military Overlay ..." layer from the TOC there is no easy way for the user to interact with it again.

#### Repro steps
1. Use MSE to search for and add a symbol to the map so that the schema will be created in your project.
2. Once the symbol is added and the schema is created, remove "Military Overlay ..." layer from the TOC
3. Try to add another symbol 

#### Expected behavior
There should be some way to link MSE, in that same project, back up with the database it creates

ArcGIS Pro 2.2
MSE build 5
MT build 43

**Comment by dfoll** [comment]
@csmoore this is a more to the point version of #176 can you take a look at it. I am also in the process of logging a problem with how the favorites works, but that one will take longer to write up. If this is not something that can be fixed before you are unavailable for the rest of the sprint please let me know

**Comment by csmoore** [comment]
This has been partially addressed in branch: https://github.com/Esri/military-symbol-editor-addin-wpf/tree/csm/%23242-removing-mo-layers-lock-up

When the user attempts to remove the layer, they now at least get a warning and the addin no longer locks up during this condition.

![image](https://user-images.githubusercontent.com/3090809/43667536-59520ffa-9746-11e8-96ac-1f055068a3c0.png)

However, a bit more work remains to add the feature class back to the map and hook back up to the renderer.

**Comment by csmoore** [comment]
This should be addressed in PR #252 

This has been changed to add warnings (and option to cancel - in comment above) when user removes the military overlay group layer. Also, adds a prompt and adds the required layer back to the map if user has removed but user then tries to add a symbol with the symbol editor.

The only difference in user experience *after the military overlay group layer has been removed*, is that only the layers required are added back to the map as new symbols are added.  For example:

![image](https://user-images.githubusercontent.com/3090809/43801972-839cd35c-9a62-11e8-95c4-cf1bbb8b8eb5.png)

This seemed preferable to just adding all of the layers back, since the extra layers might annoy a user, and be the reason why they deleted them to begin with.

**Comment by topowright** [comment]
This is been verified in the September 2018 build.
