### ISSUE TITLE
Re-purpose the military symbology repo to include schemas for ArcGIS Pro and ArcMap from mil-features-data

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#256]
wikis and readmes on how to create data model - determine if used
make necessary changes
documentation of data model - review for accuracy and update as necessary - 

- [x] Rename the repo
- [ ] ~update the url for Jenkins~

- [ ] ~Create a branch for the team to work in~ 
- [ ] ~Create a new readme landing page~
- [x] Move folder for styles #360 
https://github.com/Esri/military-features-data/tree/dev/military-symbology-styles

- [ ] Go thru the issues: 

https://github.com/Esri/military-features-data/issues
- [ ] Move all wiki items after being reviewed for clarity and need: (Move done to: https://github.com/ArcGIS/military-symbology-styles/wiki )

https://github.com/Esri/military-features-data/wiki

- [ ] Move the testing content to the testing catalog repo
- [ ] Review the Dictionary Renderer wiki
- [ ] Review the Style Design wiki: 
~https://github.com/Esri/military-features-data/wiki/Style-Design~ -> https://github.com/ArcGIS/military-symbology-styles/wiki

- [ ] ~Review the Procedures for StyleX creation and move to Solutions Defense:~ (Note: we don't have this app and steps yet from core)
- Stylx generation
- Style Editing
- Working with .csv files to generate a .stylx

Review the readmes for: 
- [x] Military Overlay
- [ ] ~Military Features~ (did not move)

Deprecate repo: 

- [ ] https://github.com/Esri/military-features-data (steps above should have moved anything still needed to https://github.com/Esri/military-symbology and https://github.com/ArcGIS/military-symbology-styles)

**Comment by dfoll** [comment]
@csmoore because of changes we made in #360  please point the add-in to use the new layer files that were moved over after it is merged - new layer files are in   ...\military-symbology\military-overlay\[standard-name]

**Comment by csmoore** [comment]
Now working on last items to complete this task:

1. Removing the duplicate layer packages at: https://github.com/Esri/military-symbology/tree/dev/source/ProSymbolEditor/LayerFiles 
2. Changing the Addin build project to grab these from the new locations ( [ex](https://github.com/Esri/military-symbology/tree/dev/military-overlay/app6d/lpkx) )
3.  Small update to the code since [this layer package was renamed in the move](https://github.com/Esri/military-symbology/tree/dev/military-overlay/mil2525b2/lpkx) (to be consistent with the other names).
