### ISSUE TITLE
Delete favorite leaves Symbol Editor in Inconsistent State

### ISSUE THREAD

**Issue by csmoore** [Esri/military-symbology#381]
When you delete a selected favorite, the Symbol Editor resets the active symbol but leaves the editor in Inconsistent State where it shows an active symbol (the Add to Map button is enabled)

Repro steps:

1. Search for a symbol (ex. Infantry)
2. Click on symbol in search list and click "Add Favorite"
3. On Favorites Tab, click on newly created favorite and click Delete
4. The Favorite is deleted
5. Go to the Symbol Tab, 
    a. the favorite that deleted still seems to be the active symbol
    b. However if you click Add to Map an Unknown Symbol is shown
6. The symbol editor is now in an inconsistent state 

![image](https://user-images.githubusercontent.com/3090809/60743909-91d72f00-9f41-11e9-93e2-609fd696e41f.png)

Expected behavior: when the favorite is deleted, the Symbol Editor should be reset and the Add To Map button should be disabled.

@dfoll found this issue while preparing a demo

**Comment by csmoore** [comment]
PR #384 created to address

**Comment by dfoll** [comment]
With MSE build 121 (released) confirmed the problem. 
Confirmed with build 136 (testing branch associated with #384 ) that add-in is reset if a favorite is deleted .

@csmoore one small change I would like to ask for. Even after the add-in is reset, the `Add Favorite` is still active. It doesn't do anything other than pop up a message saying "Invalid Favorite". Can we make the add-in so that if there is no symbol to add to favorites, that the `Add Favorite" button is disabled ( this behavior is already in place for the `Add to Map` button)

![image](https://user-images.githubusercontent.com/5322669/61718765-9e28fd80-ad31-11e9-83c4-3b81c9510529.png)
even after I clear the search bar,and nothing is in the list, the `Add Favorite` button is still active.  Also, even though it is unusable, the last symbol previewed is hanging around for some reason.

**Comment by csmoore** [comment]
Added disabling of the Add Favorite button if nothing selected in commit: https://github.com/Esri/military-symbology/commit/2d9287481e71fa05564e059f45dfa1bd16d86c9c

![image](https://user-images.githubusercontent.com/3090809/61755678-abbca280-ad86-11e9-9f63-9b4d3801ea94.png)

@dfoll ready for re-check

**Comment by dfoll** [comment]
build 137 works as expected.

**Comment by dfoll** [comment]
- [ ] add to Defense what's new for october release
- [ ] add a new row to mse homepage for october release
- [ ] add to mse october release notes
- [ ] add to mt october release notes

**Comment by dfoll** [comment]
### Doc changes:
- 
- \DefenseSolutions\MilitarySymbolEditor\October2019\Dev\139\

**Comment by csmoore** [comment]
Verified Doc:

Defense What's new page - link to bug fixes

Military Symbol Editor homepage - added to releases table:

![image](https://user-images.githubusercontent.com/3090809/62135263-e99e5700-b2af-11e9-94ad-0b8c5df01479.png)

Military Symbol Editor October Resources page - added bug to table:

![image](https://user-images.githubusercontent.com/3090809/62135107-a17f3480-b2af-11e9-886c-9eb19dee2195.png)

Military Symbol Editor in ArcGIS.pdf - added bug to table : 

![image](https://user-images.githubusercontent.com/3090809/62136340-e99f5680-b2b1-11e9-8a34-de1faa839452.png)

Military Tools homepage - added to releases table:
 
Military Tools October Resources page - added bug to Military Symbol Editor table

Military Tools for ArcGIS Release Notes.pdf 

![image](https://user-images.githubusercontent.com/3090809/62136423-1489aa80-b2b2-11e9-9901-1d3fdab548af.png)
